### PR TITLE
update to react redux 7

### PR DESCRIPTION
**Pull request by niffin**

### CODE REVIEW

**Comment by ttoohey** [comment]
I'm on the fence about whether to merge this. I'm not really sure of the motivation (there's nothing stopping you from using react-redux 7 is there?).

There are a couple of housekeeping issues though:
* react-redux 7 depends on react 16.8.4, so the react dependency would need to be updated too
* don't update the package version - you need to leave something for the maintainer to do :wink: 

I'm tempted to set the dependencies to '*' as this package is very simple and relies on pretty fundamental features of react & react-redux that any version would satisfy

**Comment by niffin** [comment]
I'm not sure what it is but after I upgraded `react`, `react-scripts`, `react-redux`, etc I've been getting  ```Uncaught Invariant Violation: Could not find "store" in either the context or props of "Connect(_class)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(_class)"``` from all the `react-redux-connect-lifecycle` `connect`s. The error goes away if I change to `react-redux`'s `connect`.

I took a shot in the dark hoping it'll fix it.

**Comment by ttoohey** [comment]
I've had a chance to reproduce those errors and have made a new version (1.0.2) that moves react & react-redux to peer dependencies and allows any version. This worked in my simple test case (the "Could not find store" message was gone).

Thanks for reporting the problem!

**Comment by niffin** [comment]
Glad to hear, and thanks for fixing the issue. I'm also happy to hear that my hunch was right(?) and I wasn't just flailing my fingers aimlessly.

We've upgraded `react-scripts` and are moving to graphQL. Between Apollo's `<Query>` component and the new react hooks there won't be a need for lifecycle methods in our containers so I'm afraid your weekly downloads are going to suffer. ;)

Anyhow it's been a pleasure submitting PRs to you and `react-redux-connect-lifecycle` has provided us with much value. Thanks and all the best. Maybe I'll see you on /r/buckethead

**Pull request closed without merging**
